# Generated by Django 4.0.4 on 2022-05-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
